### ISSUE TITLE
Returning errors to Sublime

### ISSUE THREAD

**Issue by bmix** [tylerl/FilterPipes#2]
Related to my previous issue #1, where I had to run an external command, whose output may result in two different files, one being an error-report, I would like to propose a switch, that would tell FilterPipes to open a named file after a filter-run (in this case the error-report).

When a program 'Tidy' gets run with an option '-f filespec', then all errors and warnings, that may result from this run will end up in a file designated under 'filespec'. This is in addition to the actual result of the command, which, in this case, would be a modified version of the input-document.

**Comment by tylerl** [comment]
This sounds a bit too niche an option for general use. I don't think it belongs in the base plugin, but you can certainly add this to your OWN command. Just create a command derived from FilterPipesProcessCommand and put your additional logic there:

``` python
class ProcessAndOpenFileCommand(FilterPipesProcessCommand):
    file_to_open="/foo/bar.txt"
    def run(self, edit, **settings):
        super(ProcessAndOpenFileCommand, self).run(edit,**settings)
        self.view.window().run_command('open_file',args={'file':self.file_to_open})
```

Warning: the above is TOTALLY untested; I didn't even bother to see if it was parses. But that's the idea, I think. Head over to [docs.sublimetext.info/...](http://docs.sublimetext.info/en/latest/reference/commands.html?#commands) for the SublimeText plugin API docs, and look at [filterpipes.py](https://github.com/tylerl/FilterPipes/blob/master/filterpipes.py) to see where to insert your code.

**Comment by bmix** [comment]
Ok. Thanks.
