### ISSUE TITLE
Defining current directory for external command

### ISSUE THREAD

**Issue by bmix** [tylerl/FilterPipes#3]
May I propose another setting, that defines the current-working directory for any external command to run?

**Comment by tylerl** [comment]
Added subprocess_args to FilterPipesProcessCommand. So you can call it like this:

``` json
 {
        "caption": "HTML Tidy",
        "command": "filter_pipes_process",
        "args": {
            "command": ["tidy","-config","/Users/tylerl/htmltidy.conf"],
            "shell": false,
            "expected_returns": [0,1],
            "subprocess_args": {"cwd": "/some/directory/path"}
        }
    }
```

**Comment by bmix** [comment]
Thanks for doing this!

Is there a variable, that SublimeText sets, that designates the project's/currently edited files directory? May make a nice addition for setting the current directory. However, upon a quick scan just right now, I could not find any such thing.

**Comment by tylerl** [comment]
Not really, nor is it particularly clear what that would even mean. You can have files open in _many_ directories, or your currently open file may not be saved anywhere. And projects can contain zero or more top-level directories. You can get the _current working_ directory with `os.getcwd()`, FWIW. You can try all this stuff live by opening up your python console in Sublime (<kbd>ctrl</kbd>+<kbd>`</kbd>) and just typing it in.
