### ISSUE TITLE
Command history

### ISSUE THREAD

**Issue by frizop** [tylerl/FilterPipes#4]
Would it be possible to implement a command history for this plugin? I went searching and while I don't understand plugin architecture very well I found somebody asking for the same thing:
http://www.sublimetext.com/forum/viewtopic.php?f=6&t=14777&p=59099&hilit=show_input_panel#p59099

It seems that it might be possible?

**Comment by tylerl** [comment]
It looks like the example you posted is someone who _also_ doesn't know how to implement history. Do you have an example of a plugin that does this well?

**Comment by frizop** [comment]
I don't, and I actually spent a little bit of time researching this, I'm not sure sublime supports that widget loading history or rather, there is a way to have the widget's history saved. Feel free to ignore this.

**Comment by bluefish6** [comment]
Hi, few years have passed. I'm not familiar a lot with sublime plugin development, but it seems that [`command_history` method of View class](https://www.sublimetext.com/docs/3/api_reference.html#sublime.View) may be what is needed.

@tylerl could you please take a look at it? Your plugin boosts my productivity in sublime a lot, but this one missing feature would make your plugin complete :)

**Comment by maliayas** [comment]
FYI. [This plugin](https://github.com/greneholt/SublimeExternalCommand) has a command history feature. It looks like a smart implementation and easy to copy to this plugin.
